### ISSUE TITLE
v1.5 just returns empty map

### ISSUE THREAD

**Issue by jensjeflensje** [SBDPlugins/MapReflectionAPI#20]
I'm using paper 1.19.4 550 with a 1.19.4 client and mapreflectionapi v1.5. The plugin auto-updated itself and after that, it stopped working.

The returned map is just empty. It looks like it has no data at all, or the whole image is transparent.

**Comment by stijnb1234** [comment]
Looking into it, will test myself on 1.19.4.

**Comment by stijnb1234** [comment]
Issue is related to the show in hand feature, the rest works fine.
