### ISSUE TITLE
Update jar file on spigot and maven

### ISSUE THREAD

**Issue by Caranouga** [SBDPlugins/MapReflectionAPI#5]
Hello, I saw that you have updated your api, but I wanted to know if it is up to date on spigot and on Maven?

**Comment by stijnb1234** [comment]
> Hello, I saw that you have updated your api, but I wanted to know if it is up to date on spigot and on Maven?

Not yet, I'm still testing the latest build. If there are no bugs, I will bump versions asap.
You can always download the artifact to test the latest build yourself. 

https://github.com/SBDPlugins/MapReflectionAPI/actions/runs/2762672591

**Comment by stijnb1234** [comment]
1.2 is released on Spigot and Polymart, it's also on our maven repo now.
